# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Lab
    url: 'people'
    weight: 20
  - name: Featured
    url: '#featured'
    weight: 30
  - name: Post
    url: '#posts'
    weight: 40
  - name: Project
    url: '#projects'
    weight: 50
  - name: Publication
    url: '#publications'
    weight: 60
  - name: Presentation
    url: '#talks'
    weight: 70
  - name: Teaching
    url: '#accomplishments'
    weight: 80
  - name: Gallery
    url: ''
    weight: 90
  - name: Contact
    url: '#contact'
    weight: 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
